coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 98%

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
