# Copyright 2026 Engenere - Felipe Motter Pereira
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Commercial Policy",
    "version": "16.0.2.4.2",
    "maintainers": ["felipemotter"],
    "author": "Engenere",
    "license": "AGPL-3",
    "category": "Sales",
    "summary": "Sales profiles, commercial conditions and structured discount channels",
    "website": "https://github.com/Engenere/addons-trento",
    "depends": [
        "sale_management",
        "l10n_br_sale",
        "base_partner_company_group",
        "sale_partner_company_group",
        "engenere_commission",
        "engenere_commission_partner_confirmation",
        "engenere_commission_partial_payment",
        "account_commission",
        "commission_formula",
        "account_payment_mode",
        "account_payment_sale",
        "delivery",
        "sale_stock",
        "sale_partner_incoterm",
        "eng_punctuality_discount",
        "trento_sale_usability",
        "trento_invoice_usability",
        # Provides ``external_layout_boxed_compact`` reused by the
        # sales profile and pricelist reports.
        "trento_report_utils",
        "sale_product_configurator",
        "sale_tier_validation",
        "account_move_tier_validation",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "wizards/save_condition_wizard_views.xml",
        "wizards/group_condition_wizard_views.xml",
        "wizards/reload_condition_wizard_views.xml",
        "data/decimal_precision.xml",
        "data/tier_definition.xml",
        "views/sales_profile_views.xml",
        "views/sales_profile_my_views.xml",
        "views/partner_commercial_condition_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "views/res_config_settings_views.xml",
        "views/crm_team_views.xml",
        "views/commission_views.xml",
        "views/account_move_views.xml",
        "views/product_category_views.xml",
        "views/product_configurator_templates.xml",
        "views/menu.xml",
        "data/commission_template.xml",
        "report/sale_order_report.xml",
        "report/sales_profile_report.xml",
        "report/sales_profile_report_styles.xml",
        "report/sales_profile_report_template.xml",
        "data/cron.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "tr_commercial_policy/static/src/scss/commercial_condition_form.scss",
            "tr_commercial_policy/static/src/scss/extra_discount_buttons.scss",
            "tr_commercial_policy/static/src/components/**/*.js",
            "tr_commercial_policy/static/src/components/**/*.xml",
        ],
    },
    "installable": True,
    "application": False,
}
